# rbac-jupyter-proxy.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyter-proxy-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces", "services"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services/proxy"]
    verbs: ["get"]  # needed for connect_*_service_proxy_* calls
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyter-proxy-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jupyter-proxy-reader
subjects:
  - kind: ServiceAccount
    name: jupyter-proxy
    namespace: jupyter-proxy
